trace:
  # Rules not to trace
  omit:
    - A-to-F
    - day
    - geographyPrefix
    - geometryPrefix
    - hour
    - identifierLeadingCharacter
    - identifierCharacter
    - minute
    - month
    - odataIdentifier
    - oneToNine
    - other-delims
    - pchar
    - pchar-no-SQUOTE
    - pct-encoded
    - qchar-no-AMP-EQ-AT-DOLLAR
    - second
    - sub-delims
    - unreserved
    - year
    - zeroToFiftyNine
