name: Validate Generated HTML

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      NPM_TOOL: abnf-to-railroad
      INPUT_FILE: abnf/odata-abnf-construction-rules.txt
      OUTPUT_FILE: syntax-diagram/odata-syntax.html
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install global npm tool
        run: npm install -g ${{ env.NPM_TOOL }}

      - name: Backup committed HTML
        run: |
          if [ ! -f "${{ env.OUTPUT_FILE }}" ]; then
            echo "❌ ERROR: No HTML file found in repository!"
            echo ""
            echo "The ABNF source file exists but the corresponding HTML is missing."
            echo "Please run the following commands and commit the changes:"
            echo ""
            echo "  ${{ env.NPM_TOOL }} ${{ env.INPUT_FILE }} > ${{ env.OUTPUT_FILE }}"
            echo "  git add ${{ env.OUTPUT_FILE }}"
            echo "  git commit -m 'Generate HTML syntax diagram from ABNF'"
            echo ""
            exit 1
          fi
          cp ${{ env.OUTPUT_FILE }} ${{ env.OUTPUT_FILE }}.committed

      - name: Generate fresh HTML
        run: ${{ env.NPM_TOOL }} ${{ env.INPUT_FILE }} ${{ env.OUTPUT_FILE }}

      - name: Compare files
        run: |
          if ! diff -q ${{ env.OUTPUT_FILE }}.committed ${{ env.OUTPUT_FILE }}; then
            echo "❌ ERROR: The committed HTML does not match the generated version!"
            echo ""
            echo "The HTML file is out of sync with the source text file."
            echo "Please run the following commands and commit the changes:"
            echo ""
            echo "  ${{ env.NPM_TOOL }} ${{ env.INPUT_FILE }} > ${{ env.OUTPUT_FILE }}"
            echo "  git add ${{ env.OUTPUT_FILE }}"
            echo "  git commit --amend --no-edit"
            echo ""
            exit 1
          fi
          echo "✅ HTML file is correctly generated and up to date!"
          rm ${{ env.OUTPUT_FILE }}.committed
